### ISSUE TITLE
SyntaxTree::Parser::ParseError crash in vscode

### ISSUE THREAD

**Issue by masterkain** [ruby-syntax-tree/syntax_tree#138]
I just noticed syntax_tree having an argument with the contents of this file and crashing:

```
if ::ActiveRecord.respond_to?(:use_yaml_unsafe_load)
  ::ActiveRecord.use_yaml_unsafe_load = false
  ::ActiveRecord.yaml_column_permitted_classes = [
    ::ActionController::Parameters
    ::ActiveRecord::Type::Time::Value,
    ::ActiveSupport::HashWithIndifferentAccess
    ::ActiveSupport::TimeWithZone,
    ::ActiveSupport::TimeZone,
    ::BigDecimal,
    ::Date,
    ::Symbol,
    ::Time,
  ]
end
```

it crashes even if stripped down of `::`, not sure what's going on.

```
/Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree/parser.rb:2474:in `on_parse_error': syntax error, unexpected :: at EXPR_BEG, expecting ']' (SyntaxTree::Parser::ParseError)
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree.rb:46:in `parse'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree.rb:46:in `parse'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree.rb:53:in `format'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree/language_server.rb:101:in `format'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree/language_server.rb:59:in `run'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/lib/syntax_tree/cli.rb:310:in `run'
	from /Users/kain/.rvm/gems/ruby-3.0.0/gems/syntax_tree-3.3.0/exe/stree:9:in `<top (required)>'
	from /Users/kain/.rvm/gems/ruby-3.0.0/bin/stree:23:in `load'
	from /Users/kain/.rvm/gems/ruby-3.0.0/bin/stree:23:in `<main>'
[Info  - 8:43:17 PM] Connection to server got closed. Server will restart.
```

**Comment by masterkain** [comment]
ops, my bad
