### ISSUE TITLE
Code causes syntax tree to crash

### ISSUE THREAD

**Issue by vwall** [ruby-syntax-tree/syntax_tree#160]
Looking at this issue https://github.com/ruby-syntax-tree/syntax_tree/issues/129 and it seems to work correctly from the CLI

example code: 
```
LongRecordName.transaction do
  LongRecordName
    .joins(:other_record)
    # rubocop:disable Rails/SkipsModelValidations

    .update_all(foo: 'bar')
end
```
CLI:
```
Error: Cannot find expected end
> 1 | LongRecordName.transaction do
    |                            ^
  2 |   LongRecordName
  3 |     .joins(:other_record)
  4 |     # rubocop:disable Rails/SkipsModelValidations
The listed files did not match the expected format.
```

However in vscode it crashes synax-tree and there is nothing indicating that something is wrong.  Is this the correct behavior?

VSCODE:
```
/Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree/parser.rb:251:in `find_token': Cannot find expected end (SyntaxTree::Parser::ParseError)
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree/parser.rb:1242:in `on_do_block'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree.rb:47:in `parse'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree.rb:47:in `parse'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree.rb:54:in `format'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree/language_server.rb:90:in `format'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree/language_server.rb:59:in `run'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/lib/syntax_tree/cli.rb:410:in `run'
	from /Users/nix/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-3.6.0/exe/stree:9:in `<top (required)>'
	from /Users/nix/.asdf/installs/ruby/3.1.2/bin/stree:25:in `load'
	from /Users/nix/.asdf/installs/ruby/3.1.2/bin/stree:25:in `<main>'
[Info  - 5:29:20 PM] Connection to server got closed. Server will restart.
```

**Comment by vwall** [comment]
It seemed like vscode-prettier handled this sort of stuff well.  SyntaxTree crashes on any syntax error with no UI warning.  Even simple things like this crash it instead of fixing.  Is this the intended behavior? 

`has_many :steps through: :user_topics`

**Comment by kddnewton** [comment]
No, the intended behavior is to not have it crash when there's a syntax error. Would you be able to attempt a PR? It would involve handling the parser error on that line I linked.
