### ISSUE TITLE
Erroring out when parsing using multiple processes

### ISSUE THREAD

**Issue by faraaz-deepsource** [ruby-syntax-tree/syntax_tree#240]
When I try to parse with SyntaxTree from within the `parallel` gem, like so:

```ruby
Parallel.map(Dir.glob('./**/*.rb')) { |file| SyntaxTree.parse(SyntaxTree.read(file)) }
```

It always errors out giving this error
```
no _dump_data is defined for class SyntaxTree::Parser (TypeError)
```

Full Stack Trace: 
```
/Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `dump': no _dump_data is defined for class SyntaxTree::Parser (TypeError)
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `process_incoming_jobs'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	from (irb):4:in `<top (required)>'                                                                   
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `eval'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/context.rb:502:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:590:in `block (2 levels) in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:779:in `signal_status'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:569:in `block in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:267:in `block (2 levels) in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `loop'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `block in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:568:in `eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:502:in `block in run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:419:in `start'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/exe/irb:11:in `<top (required)>'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
/Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `dump': no _dump_data is defined for class SyntaxTree::Parser (TypeError)
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `process_incoming_jobs'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	from (irb):4:in `<top (required)>'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `eval'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/context.rb:502:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:590:in `block (2 levels) in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:779:in `signal_status'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:569:in `block in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:267:in `block (2 levels) in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `loop'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `block in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:568:in `eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:502:in `block in run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:419:in `start'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/exe/irb:11:in `<top (required)>'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
/Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `dump': no _dump_data is defined for class SyntaxTree::Parser (TypeError)
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:566:in `process_incoming_jobs'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
	from (irb):4:in `<top (required)>'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `eval'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/workspace.rb:119:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/context.rb:502:in `evaluate'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:590:in `block (2 levels) in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:779:in `signal_status'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:569:in `block in eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:267:in `block (2 levels) in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `loop'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:249:in `block in each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb/ruby-lex.rb:248:in `each_top_level_statement'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:568:in `eval_input'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:502:in `block in run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `catch'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:501:in `run'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/lib/irb.rb:419:in `start'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.5.0/exe/irb:11:in `<top (required)>'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /Users/faraaz/.rbenv/versions/3.1.2/bin/irb:25:in `<main>'
/Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:86:in `rescue in work': Parallel::DeadWorker (Parallel::DeadWorker)
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:83:in `work'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:482:in `block (4 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:481:in `block (3 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `loop'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `block (2 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:222:in `block (4 levels) in in_threads'
<internal:marshal>:34:in `load': end of file reached (EOFError)
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:84:in `work'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:482:in `block (4 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:597:in `with_instrumentation'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:481:in `block (3 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `loop'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:469:in `block (2 levels) in work_in_processes'
	from /Users/faraaz/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:222:in `block (4 levels) in in_threads'
```

This doesn't happen when I use threads instead.

**Comment by kddnewton** [comment]
Yeah this is because `ripper` doesn't define how to dump its data. You can see here:

```ruby
Marshal.dump(Ripper.new("abc"))
# => no _dump_data is defined for class Ripper (TypeError)
```

We're entirely dependent on ripper providing that functionality at the moment until we have a new parser, so I'm not going to be able to fix this. If you want it fixed, you should open an issue on ruby/ruby to add that ability.
