### ISSUE TITLE
Parsing code that has embdoc between method chain fails with undefined method `leading!'

### ISSUE THREAD

**Issue by tompng** [ruby-syntax-tree/syntax_tree#274]
Here is the input code
```ruby
self.
=begin
=end
to_s
```

And the result
```
% cat a.rb
self.
=begin
=end
to_s
% stree ast a.rb
undefined method `leading!' for #<SyntaxTree::EmbDoc:0x00000001053fe930 @value="=begin\n=end", @location=#<SyntaxTree::Location:0x000000010518a910 @start_line=2, @start_char=6, @start_column=0, @end_line=3, @end_char=17, @end_column=4>>
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/parser.rb:2734:in `block in attach_comments'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/parser.rb:2715:in `each'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/parser.rb:2715:in `attach_comments'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/parser.rb:2707:in `on_program'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree.rb:75:in `parse'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree.rb:75:in `parse'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/cli.rb:122:in `run'
/Users/tomoya/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/syntax_tree-5.3.0/lib/syntax_tree/cli.rb:580:in `block (2 levels) in process_queue'
```

These code also failed
```ruby
def
=begin
=end
a
end
```

```ruby
def a()
=begin
=end
=1
```

```ruby
if
=begin
=end
true
end
```

```ruby
:\
=begin
=end
symbol
```

**Comment by kddnewton** [comment]
Thanks! I'll get these fixed.
