### ISSUE TITLE
PrettyPrintVisitor raises "private method `pp' called"

### ISSUE THREAD

**Issue by wenderjean** [ruby-syntax-tree/syntax_tree#310]
Trying to execute the snippet below I received `visitor/pretty_print_visitor.rb:48:in 'field': private method 'pp' called for PrettyPrint` from this line [pretty_print_visitor.rb#L47](https://github.com/ruby-syntax-tree/syntax_tree/blob/main/lib/syntax_tree/pretty_print_visitor.rb#L47).

```ruby
PP.format([], 80) do |q|
  source = '1+1'
  SyntaxTree.parse(source).pretty_print(q)
end.join
```

```
/home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/visitor/pretty_print_visitor.rb:48:in `field': private method `pp' called for #<PrettyPrint:0x00007f280df96a00 @output=["(", "program"], @maxwidth=80, @newline="\n", @genspace=#<Proc:0x00007f280df96ac8 /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:45 (lambda)>, @output_width=8, @buffer_width=1, @buffer=[#<PrettyPrint::Breakable:0x00007f280df99f48 @obj=" ", @width=1, @pp=#<PrettyPrint:0x00007f280df96a00 ...>, @indent=2, @group=#<PrettyPrint::Group:0x00007f280df9a650 @depth=1, @breakables=[#<PrettyPrint::Breakable:0x00007f280df99f48 ...>], @break=false>>], @group_stack=[#<PrettyPrint::Group:0x00007f280df968c0 @depth=0, @breakables=[], @break=false>], @group_queue=#<PrettyPrint::GroupQueue:0x00007f280df96730 @queue=[[#<PrettyPrint::Group:0x00007f280df968c0 @depth=0, @breakables=[], @break=false>], [#<PrettyPrint::Group:0x00007f280df9a650 @depth=1, @breakables=[#<PrettyPrint::Breakable:0x00007f280df99f48 @obj=" ", @width=1, @pp=#<PrettyPrint:0x00007f280df96a00 ...>, @indent=2, @group=#<PrettyPrint::Group:0x00007f280df9a650 ...>>], @break=false>]]>, @indent=0> (NoMethodError)

        q.pp(value)
         ^^^
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/visitor/field_visitor.rb:660:in `block in visit_program'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/visitor/pretty_print_visitor.rb:59:in `block in node'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:253:in `block (2 levels) in group'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:280:in `nest'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:252:in `block in group'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:265:in `group_sub'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:251:in `group'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/visitor/pretty_print_visitor.rb:57:in `node'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/visitor/field_visitor.rb:659:in `visit_program'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/node.rb:8502:in `accept'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/basic_visitor.rb:67:in `visit'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/syntax_tree-5.3.0/lib/syntax_tree/node.rb:131:in `pretty_print'
	from (irb):13:in `block in <top (required)>'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/prettyprint.rb:47:in `format'
	from (irb):11:in `<main>'
	from /home/dev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	... 2 levels...
irb(main):015:0> 
```

Ruby version 3.1.2
SyntaxTree 5.3.0 or head

**Comment by kddnewton** [comment]
Yeah that's expected. The `PP.format` method called `PrettyPrint.format` which yields `PrettyPrint` object to the block, which can't be used in a lot of circumstances.

See for example:

```ruby
PP.format([], 80) { |q| [].pretty_print(q) }.join
```

It fails with `q.seplist` being undefined because that method is defined on `PP`, not `PrettyPrint`. In general you shouldn't use `PrettyPrint.format` unless you have very simple objects.
